version: '3.9'
services:
  organization-dashboard:
    build:
      context: .
      args:
        - REACT_APP_ENVIRONMENT=development
    volumes:
      - "./conf/nginx.dev.conf:/etc/nginx/nginx.conf"
    ports:
      - "3030:80"

networks:
  default:
    name: swsp
