name: audit

on: [pull_request] 

jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
  build:
    name: Build with Node
    runs-on: ubuntu-latest
    steps:
      - name: Development Code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
          
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build --if-present
        env:
          CI: false
      
      - name: Check linting and formatting
        # Custom script for checking the linting and formatting being in place
        run: npm run lint

      - name: Persist workflow data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: organisation-dashboard-audit-artifact
          path: ./build
