name: Pull Request

on: [pull_request]

jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present
        env:
          CI: false

      - name: Check linting and formatting
        # Custom script for checking the linting and formatting being in place
        run: npm run lint

      - name: Persist workflow data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: organisation-dashboard-artifact
          path: ./build

  codeQL-analyse:
    name: CodeQL-Analyse
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
